import fs from "node:fs/promises";
import path from "node:path";
import { createAdminClient } from "@/lib/supabase/admin";
import { getSettings, formatUsd } from "@/lib/settings";
import { getResend } from "@/lib/email/resend";
import { renderEmail, detailsTable, buttonRow, escapeHtml } from "@/lib/email/shell";
import { buildBookingIcs } from "@/lib/ics";
import { SERVICE_AGREEMENT_PDF_FILENAME } from "@/lib/agreement";
import { arrivalBlockLabel, ARRIVAL_BLOCKS } from "@/lib/schedule/blocks";
import { formatVisitDate } from "@/lib/format";
import { denverLocalToUtc } from "@/lib/time/denver";
import { getAppBaseUrl } from "@/lib/url";
import type { BuiltEmail } from "@/lib/email/types";

type JobRow = {
  id: string;
  scheduled_date: string;
  arrival_block: number;
  blocks_needed: number;
  quoted_price_cents: number | null;
  access_token: string | null;
  property:
    | { address: string; customer: Cust | null }
    | { address: string; customer: Cust | null }[]
    | null;
};
type Cust = { full_name: string | null; email: string | null };

function flatten<T>(v: T | T[] | null | undefined): T | null {
  return Array.isArray(v) ? v[0] ?? null : v ?? null;
}

// The static, version-stamped agreement PDF (generated by
// `npm run agreement:pdf`, committed under /content, bundled into the /book
// server trace via next.config.mjs). Read once per warm instance.
let agreementPdfCache: Buffer | null = null;
async function readAgreementPdf(): Promise<Buffer | null> {
  if (agreementPdfCache) return agreementPdfCache;
  try {
    const file = path.join(process.cwd(), "content", SERVICE_AGREEMENT_PDF_FILENAME);
    agreementPdfCache = await fs.readFile(file);
    return agreementPdfCache;
  } catch (err) {
    console.error(
      "readAgreementPdf: could not read",
      SERVICE_AGREEMENT_PDF_FILENAME,
      err
    );
    return null;
  }
}

// "cluster_matched": sent after the customer explicitly ACCEPTS a
// geographic-clustering suggestion via /cluster-consent/[token] — unlike
// "rescheduled" (the customer just picked this themselves) or
// "owner_rescheduled" (the owner already moved it, notify-only), the
// customer here made an affirmative choice to move their own visit for a
// suggestion Uinta Ice proposed, so it gets its own thank-you-voiced copy.
export type ConfirmationVariant = "new" | "rescheduled" | "owner_rescheduled" | "cluster_matched";

// Assemble the confirmation email (spec §8.1): date, arrival window, address,
// price, magic link, .ics invite. Split from the send so it can be previewed.
// `variant: "rescheduled"` re-sends after a magic-link reschedule — same
// content, updated heading, and an .ics SEQUENCE bump so calendars replace the
// existing entry rather than add a duplicate (stable UID does the matching).
// `variant: "owner_rescheduled"` is the same .ics-replacement mechanics but
// for the other direction — the owner/tech moved the job's date or arrival
// window directly in the field app (see uinta-field-app's job edit page and
// POST /api/internal/owner-reschedule-notify below). "rescheduled"'s copy is
// written as if the customer just did it themselves ("Your visit has been
// rescheduled") on the confirmation page they were just looking at — reused
// here it would read as if the customer took an action they didn't take, so
// this gets its own owner-voiced copy ("We've updated your appointment").
export async function buildBookingConfirmationEmail(
  jobId: string,
  opts?: { variant?: ConfirmationVariant; attachAgreement?: boolean }
): Promise<BuiltEmail | { error: string }> {
  const variant: ConfirmationVariant = opts?.variant ?? "new";
  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from("jobs")
    .select(
      "id, scheduled_date, arrival_block, blocks_needed, quoted_price_cents, access_token, " +
        "property:properties(address, customer:customers(full_name, email))"
    )
    .eq("id", jobId)
    .single();

  if (error || !data) return { error: `job not found: ${error?.message ?? jobId}` };

  const job = data as unknown as JobRow;
  const property = flatten(job.property);
  const customer = flatten(property?.customer);
  if (!customer?.email) return { error: "customer has no email" };

  const settings = await getSettings();
  const block = ARRIVAL_BLOCKS.find((b) => b.index === job.arrival_block);
  const windowLabel = arrivalBlockLabel(job.arrival_block, job.blocks_needed);
  const dateLong = formatVisitDate(job.scheduled_date, { withYear: true });
  const priceText = formatUsd(job.quoted_price_cents ?? settings.base_price_cents);
  const address = property?.address ?? "";
  const name = customer.full_name?.trim() || "there";

  const baseUrl = await getAppBaseUrl();
  const manageUrl = job.access_token ? `${baseUrl}/visit/${job.access_token}` : baseUrl;

  const start = block ? denverLocalToUtc(job.scheduled_date, block.startsAt) : new Date();
  const end = block ? denverLocalToUtc(job.scheduled_date, block.endsAt) : new Date();
  const ics = buildBookingIcs({
    uid: `job-${job.id}@uintaice.com`,
    start,
    end,
    summary: "Uinta Ice Co — ice machine cleaning",
    description: `Arrival window ${windowLabel}. Manage this visit: ${manageUrl}`,
    location: address,
    organizerEmail: settings.business_email,
    organizerName: settings.business_name,
    // Monotonic (minutes since epoch) so a rescheduled invite always outranks
    // the previous one in calendar clients. "new" stays at 0.
    sequence: variant !== "new" ? Math.floor(Date.now() / 60000) : 0,
  });

  const headline =
    variant === "rescheduled"
      ? "Your visit has been rescheduled."
      : variant === "owner_rescheduled"
        ? "We've updated your appointment."
        : variant === "cluster_matched"
          ? "Your visit has been moved — thanks for helping us out."
          : "Your cleaning is booked.";

  const inner = `
    <p style="margin:0 0 12px;">Hi ${escapeHtml(name)},</p>
    <p style="margin:0 0 4px;font-size:16px;font-weight:700;">${escapeHtml(headline)}</p>
    <p style="margin:0 0 12px;color:#5b6470;">Your card isn&rsquo;t charged until after the visit.</p>
    ${detailsTable([
      { label: "Date", value: dateLong },
      { label: "Arrival window", value: windowLabel },
      { label: "Address", value: address },
      { label: "Price", value: `${priceText} per visit` },
    ])}
    ${buttonRow(manageUrl, "Reschedule or cancel")}
    <p style="margin:12px 0 0;color:#5b6470;font-size:13px;">An updated calendar invite is attached. Your reschedule / cancel link expires the day after the visit.</p>
  `;

  const title =
    variant === "rescheduled"
      ? "Your Uinta Ice Co visit was rescheduled"
      : variant === "owner_rescheduled"
        ? "Your Uinta Ice Co appointment was updated"
        : variant === "cluster_matched"
          ? "Your Uinta Ice Co visit was moved"
          : "Your Uinta Ice Co cleaning is booked";

  const html = renderEmail({
    title,
    preheader: `${dateLong}, ${windowLabel} — ${address}`,
    inner,
  });

  const text = [
    `Hi ${name},`,
    ``,
    variant === "rescheduled"
      ? `Your Uinta Ice Co visit has been rescheduled.`
      : variant === "owner_rescheduled"
        ? `We've updated your Uinta Ice Co appointment.`
        : variant === "cluster_matched"
          ? `Your Uinta Ice Co visit has been moved — thanks for helping us out.`
          : `Your Uinta Ice Co cleaning is booked.`,
    ``,
    `Date:           ${dateLong}`,
    `Arrival window: ${windowLabel}`,
    `Address:        ${address}`,
    `Price:          ${priceText} per visit`,
    ``,
    `Reschedule or cancel: ${manageUrl}`,
    `(This link expires the day after your visit.)`,
    ``,
    `Your card isn't charged until after the visit.`,
    ``,
    `— Uinta Ice Co`,
  ].join("\n");

  const attachments: NonNullable<BuiltEmail["attachments"]> = [
    { filename: "uinta-ice-visit.ics", content: Buffer.from(ics, "utf-8") },
  ];
  if (opts?.attachAgreement) {
    const pdf = await readAgreementPdf();
    if (pdf) {
      attachments.push({ filename: SERVICE_AGREEMENT_PDF_FILENAME, content: pdf });
    }
  }

  return {
    to: customer.email,
    replyTo: settings.business_email ?? undefined,
    subject:
      variant === "rescheduled"
        ? `Your Uinta Ice Co visit was moved — ${formatVisitDate(job.scheduled_date)}`
        : variant === "owner_rescheduled"
          ? `Your Uinta Ice Co appointment was updated — ${formatVisitDate(job.scheduled_date)}`
          : variant === "cluster_matched"
            ? `Your Uinta Ice Co visit was moved — ${formatVisitDate(job.scheduled_date)}`
            : `Your Uinta Ice Co cleaning is booked — ${formatVisitDate(job.scheduled_date)}`,
    html,
    text,
    attachments,
  };
}

// Returns true only if Resend accepted the send — the caller stamps
// confirmation_sent_at on true. Never throws.
export async function sendBookingConfirmationEmail(
  jobId: string,
  opts?: { overrideTo?: string; variant?: ConfirmationVariant; attachAgreement?: boolean }
): Promise<boolean> {
  try {
    const resend = getResend();
    if (!resend) {
      console.error("sendBookingConfirmationEmail: Resend not configured", { jobId });
      return false;
    }
    const built = await buildBookingConfirmationEmail(jobId, {
      variant: opts?.variant,
      attachAgreement: opts?.attachAgreement,
    });
    if ("error" in built) {
      console.error("sendBookingConfirmationEmail:", built.error, { jobId });
      return false;
    }
    const { error } = await resend.client.emails.send({
      from: resend.from,
      to: opts?.overrideTo ?? built.to,
      ...(built.replyTo ? { replyTo: built.replyTo } : {}),
      subject: built.subject,
      html: built.html,
      text: built.text,
      attachments: built.attachments,
    });
    if (error) {
      console.error("sendBookingConfirmationEmail: Resend send failed", error, { jobId });
      return false;
    }
    return true;
  } catch (err) {
    console.error("sendBookingConfirmationEmail: unexpected error", err, { jobId });
    return false;
  }
}
